---
title: "Lab 5"
author: "Lucas Vieira"
output: html_document
---

## https://github.com/hadrizia/data-analysis-labs/blob/master/Lab03/Lab03-Hadrizia.Rmd
## https://www.r-bloggers.com/dealing-with-unbalanced-data-in-machine-learning/

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
```

## Lendo os dados de treino e teste
```{r}
input <- read.csv("train.csv")
#test_data <- read.csv("test.csv")
```

## Removendo variáveis categóricas dos dados de treino, pois são irrelevantes para a regressão
```{r}
input <- input %>% select(-nome, -uf, -estado_civil, 
                          -partido, -ocupacao,-ano, 
                          -cargo,-grau,-sexo, 
                          -sequencial_candidato)
```

```{r}
dataPartition <- createDataPartition(y = input$situacao, p=0.75, list=FALSE)

set.seed(9560)
## separando o dataframe em treino e teste
train_data <- input[dataPartition, ]
test_data <- input[-dataPartition, ]
```

## First question
```{r}
input %>% group_by(situacao) %>% 
  summarise(p_eleitos=(n()/nrow(input) * 100)) %>% 
  ggplot(aes(x=situacao, y=p_eleitos, fill=situacao)) + geom_col()
```

An unbalanced dataset will bias the prediction model towards the more common class!

## Second question
```{r}
# usando validação cruzada 10-fold com 5 repetições
fitControl <- trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 5,
                           classProbs = TRUE)
```

```{r}
k <- expand.grid(k = seq(20, 100, length=81))
model_knn <- train(situacao ~ ., 
                     data = input, 
                     method = "knn", 
                     tuneGrid = k,
                     preProc = c("center", "scale"),
                     trControl = fitControl)
plot(model_knn)
```

```{r warning=FALSE} 
# logistic regression
reg_logistica <- glm(formula=situacao~., data = train_data, family=binomial)

#https://stat.ethz.ch/pipermail/r-help/2007-March/126643.html -- response type
final <- data.frame(actual = test_data$situacao,
                    predict(reg_logistica, newdata = test_data, type = "response"))
colnames(final)[colnames(final)=="predict.reg_logistica..newdata...test_data..type....response.."] <- "value"
 
final$predict <- ifelse(final$value > 0.5, "eleito", "nao_eleito")

summary(reg_logistica)
```

